name: firebase
description: A new Flutter project.
publish_to: "none"
version: 0.1.0

environment:
  sdk: ">=3.0.2 <4.0.0"

dependencies:
  cloud_firestore: ^4.8.0
  flutter:
    sdk: flutter
  http: ^1.0.0

  flutter_launcher_icons: ^0.13.1
  flutter_native_splash: ^2.3.0
  firebase_core: ^2.13.0
  firebase_auth: ^4.6.1
  flutter_spinkit: ^5.2.0

  font_awesome_flutter: ^10.4.0
  google_fonts: ^4.0.5

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0

flutter:
  uses-material-design: true
  assets:
    - assets/images/italian_food.jpg
    - assets/images/recovery.png
    - assets/images/user.png
    - assets/images/2.png
    - assets/images/logo.png
    - assets/images/italy.png
    - assets/images/japan.png
    - assets/images/mexico.png
    - assets/images/germany.png

flutter_native_splash:
  image: "assets/images/logo_v.png"
  color: "#750006"
  android: true
  ios: true
  fill: true

flutter_icons:
  image_path: "assets/images/logo_v.png"
  ios: true
  remove_alpha_ios: true
  android: "launcher_icon"
  adaptative_icon_background: "#750006"
  adaptative_icon_foreground: "assets/images/logo_v.png"
